from enum import Enum
class Item(Enum):

    ITEM_BOMB = 0
    ITEM_FLAME = 1
    ITEM_SUPERFLAME = 2
    ITEM_SPEEDUP = 3
    ITEM_DISEASE = 4
    ITEM_RANDOM = 5
    ITEM_SPRING = 6
    ITEM_SHOE = 7
    ITEM_MULTIBOMB = 8
    ITEM_BOXING_GLOVE = 9
    ITEM_DETONATOR = 10
    ITEM_THROWING_GLOVE = 11
