from positionable import Positionable

class Player(Positionable):
  # possible player states
  STATE_IDLE_UP = 0
  STATE_IDLE_RIGHT = 1
  STATE_IDLE_DOWN = 2
  STATE_IDLE_LEFT = 3
  STATE_WALKING_UP = 4
  STATE_WALKING_RIGHT = 5
  STATE_WALKING_DOWN = 6
  STATE_WALKING_LEFT = 7
  STATE_IN_AIR = 8
  STATE_TELEPORTING = 9
  STATE_DEAD = 10

  DISEASE_NONE = 0
  DISEASE_DIARRHEA = 1
  DISEASE_SLOW = 2
  DISEASE_REVERSE_CONTROLS = 3
  DISEASE_SHORT_FLAME = 4
  DISEASE_SWITCH_PLAYERS = 5
  DISEASE_FAST_BOMB = 6
  DISEASE_NO_BOMB = 7
  DISEASE_EARTHQUAKE = 8

  INITIAL_SPEED = 3
  SLOW_SPEED = 1.5
  MAX_SPEED = 10
  SPEEDUP_VALUE = 1
  DISEASE_TIME = 20000
  
  JUMP_DURATION = 2000
  TELEPORT_DURATION = 1500